version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tramitarte_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init.sh:/docker-entrypoint-initdb.d/01_init.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_tramitarte
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend 
    container_name: backend_tramitarte
    ports:
      - "8000:8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/TramitarteApp 
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend 
    container_name: frontend_tramitarte
    ports:
      - "3000:3000" 
    depends_on:
      - backend 
    volumes:
      - ./frontend:/app

volumes:
  db:
  pgadmin-data: